# Generated by Django 6.0.3 on 2026-03-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Login username', max_length=50, unique=True)),
                ('password_hash', models.CharField(help_text="Bcrypt hashed password (via Django's make_password)", max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('hr_admin', 'HR Admin'), ('hr_staff', 'HR Staff'), ('viewer', 'Viewer')], default='hr_staff', help_text='superadmin = IT full access | hr_admin = all HR modules | hr_staff = view + encode | viewer = own records only', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Account active status')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(blank=True, help_text='NULL if this account belongs to an IT admin who is not a BFAR employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_user', to='employees.employee')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'system_users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('signature_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='ZENAIDA S. SIMON', help_text='Printed name e.g. ZENAIDA S. SIMON', max_length=200)),
                ('display_title', models.CharField(default='Administrative Officer V', help_text='e.g. Administrative Officer V', max_length=200)),
                ('signature_image', models.BinaryField(blank=True, help_text='Uploaded image of handwritten signature (optional). Stored as binary — activate when confirmed by client.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this signature is currently in use on printed documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Whose signature this is', on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='accounts.systemuser')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'db_table': 'signatures',
                'ordering': ['-is_active', 'display_name'],
            },
        ),
    ]
