# Generated by Django 6.0.3 on 2026-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='personal_email',
            field=models.EmailField(blank=True, default='', help_text='Off-system personal email used ONLY for password-reset links. Required so the user recover their own account.', max_length=254),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiry - 1 hour from generation', null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='reset_token_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hex of the one-time reset token', max_length=64),
        ),
    ]
