# Generated by Django 6.0.3 on 2026-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemuser_personal_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag — deleted accounts are hidden but kept for audit trail'),
        ),
    ]
