# Generated by Django 6.0.3 on 2026-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='reset_token_issued_at',
            field=models.DateTimeField(blank=True, help_text='Whent the last reset token was issued — used for resend cooldown', null=True),
        ),
    ]
