# Generated by Django 6.0.3 on 2026-03-10 14:32

import apps.leaves.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndertimeConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_type', models.CharField(choices=[('HOURS', 'Hours'), ('MINUTES', 'Minutes')], help_text="'HOURS' (1–8) or 'MINUTES' (1–60)", max_length=10)),
                ('value', models.IntegerField(help_text='Number of hours (1–8) or minutes (1–60)')),
                ('equivalent_day', models.DecimalField(decimal_places=3, help_text='Fraction of a working day. e.g. 1 min=0.002 | 30 min=0.062 | 1 hr=0.125 | 4 hrs=0.500 | 8 hrs=1.000', max_digits=6)),
            ],
            options={
                'verbose_name': 'Undertime Conversion',
                'verbose_name_plural': 'Undertime Conversions',
                'db_table': 'undertime_conversion',
                'ordering': ['unit_type', 'value'],
                'unique_together': {('unit_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='LeaveCredit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('VL', 'Vacation Leave'), ('SL', 'Sick Leave')], help_text='VL = Vacation Leave | SL = Sick Leave', max_length=2)),
                ('year', models.IntegerField(help_text='Calendar year e.g. 2025')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Calendar month number (1–12)')),
                ('earned', models.DecimalField(decimal_places=3, default=Decimal('1.250'), help_text='Credits earned this month. Default = 1.25. First month is prorated based on date_hired (set by engine.py).', max_digits=6)),
                ('undertime_days', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='UT fraction deducted. Sourced from UndertimeConversion lookup. e.g. UT=4hrs → 0.500', max_digits=6)),
                ('abs_wp', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Absences Without Pay in fraction of a day. If leave credits = 0 and employee is absent, deducted from salary instead.', max_digits=6)),
                ('special_leave_used', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='SPL or other special leave used this month in days', max_digits=6)),
                ('special_leave_label', models.CharField(blank=True, help_text='e.g. SPL (2-0-0) | SPL (1-0-0)', max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=3, help_text='Running balance: prev_balance + earned - undertime_days - abs_wp - special_leave_used', max_digits=6)),
                ('remarks', models.TextField(blank=True, help_text="HR notes e.g. 'NO OUT July 21' | 'Oct. 24 no PM in' | 'Dec. 26-27 absent'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Permanent employee only — COS/JO have no leave credits', on_delete=django.db.models.deletion.PROTECT, related_name='leave_credits', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Leave Credit',
                'verbose_name_plural': 'Leave Credits',
                'db_table': 'leave_credits',
                'ordering': ['employee__last_name', 'leave_type', '-year', '-month'],
                'unique_together': {('employee', 'leave_type', 'year', 'month')},
            },
            bases=(apps.leaves.models.PhilippinesTimeMixin, models.Model),
        ),
    ]
