# Generated by Django 6.0.3 on 2026-03-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('to_id', models.AutoField(primary_key=True, serialize=False)),
                ('to_code', models.CharField(help_text='Format: TO#26-02-1375HR or TT#26-02-XXXX', max_length=50)),
                ('ticket_type', models.CharField(choices=[('TO', 'Travel Order'), ('TT', 'Trip Ticket')], help_text='TO = Travel Order (all employees) | TT = Trip Ticket (drivers only)', max_length=2)),
                ('destination', models.CharField(blank=True, help_text='Where the employee is traveling', max_length=200, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of travel', null=True)),
                ('date_from', models.DateField(help_text='Start date of travel')),
                ('date_to', models.DateField(help_text='End date of travel (max 5 days from date_from)')),
                ('time_from', models.TimeField(blank=True, help_text='Start time if partial-day TO', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='End time if partial-day TO', null=True)),
                ('with_overtime', models.BooleanField(default=False, help_text='Whether overtime is included in this TO')),
                ('ot_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Manual OT hours entered by HR if with_overtime = True', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='HR staff who encoded this TO/TT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encoded_travel_orders', to='accounts.systemuser')),
                ('employee', models.ForeignKey(help_text='The employee covered by this TO or TT', on_delete=django.db.models.deletion.PROTECT, related_name='travel_orders', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Travel Order',
                'verbose_name_plural': 'Travel Orders',
                'db_table': 'travel_orders',
                'ordering': ['-date_from', 'employee__last_name'],
            },
        ),
    ]
