# Generated by Django 6.0.3 on 2026-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(help_text='e.g. Independence Day, Holy Wednesday, Pampanga Day', max_length=200)),
                ('holiday_date', models.DateField(help_text='The actual holiday date', unique=True)),
                ('holiday_type', models.CharField(choices=[('regular', 'Regular Holiday'), ('special', 'Special Non-Working Holiday'), ('local', 'Local Holiday')], help_text='regular = Regular Holiday per PH law | special = Special Non-Working | local = Declared by LGU or agency', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['holiday_date'],
            },
        ),
    ]
