# Generated by Django 6.0.3 on 2026-03-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_affected', models.CharField(help_text='Name of the DB table that was changed. e.g. dtr_records, payroll_records, leave_credits', max_length=50)),
                ('record_id', models.IntegerField(help_text='The primary key value of the affected record')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('print', 'Print')], help_text='The type of action performed', max_length=10)),
                ('old_value', models.JSONField(blank=True, help_text="Full JSON snapshot of the record BEFORE the change. NULL for 'create' actions.", null=True)),
                ('new_value', models.JSONField(blank=True, help_text="Full JSON snapshot of the record AFTER the change. NULL for 'delete' actions.", null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='Exact UTC timestamp of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the workstation that was used', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for correction — MANDATORY if the record was already approved/locked before this edit. Enforced at the view level.', null=True)),
                ('performed_by', models.ForeignKey(help_text='The system user who performed this action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='accounts.systemuser')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
