# Generated by Django 6.0.3 on 2026-03-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUserActivityLog',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('attempted_username', models.CharField(blank=True, help_text='The username string attempted - useful for failed login forensics', max_length=50, null=True)),
                ('action', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('login_failed', 'Failed Login Attemp'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('account_locked', 'Account Locked')], max_length=30)),
                ('description', models.TextField(blank=True, help_text="Optional detail e.g. 'Account locked after 5 failed attempts'", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Browser / client_info', null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL on failed login if the username does not exists in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.systemuser')),
            ],
            options={
                'verbose_name': 'System User Activity Log',
                'verbose_name_plural': 'System User Activity Logs',
                'db_table': 'system_user_activity_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
