# Generated by Django 6.0.3 on 2026-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_systemuseractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable summary of what was done. Auto-generated or manually set.', null=True),
        ),
    ]
