# Generated by Django 6.0.3 on 2026-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_add_description_to_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuseractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('login_failed', 'Failed Login Attemp'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked')], max_length=30),
        ),
    ]
