# Generated by Django 6.0.3 on 2026-03-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_reset_token_issued_at'),
        ('audit', '0004_alter_systemuseractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='The system user who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.systemuser'),
        ),
    ]
