# Generated by Django 6.0.3 on 2026-03-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRRecord',
            fields=[
                ('dtr_id', models.AutoField(primary_key=True, serialize=False)),
                ('dtr_date', models.DateField(help_text='The date of this attendance record')),
                ('am_in', models.DateTimeField(blank=True, help_text='Biometric scan timestamp for AM time-in', null=True)),
                ('am_out', models.DateTimeField(blank=True, help_text='Biometric scan timestamp for AM time-out', null=True)),
                ('pm_in', models.DateTimeField(blank=True, help_text='Biometric scan timestamp for PM time-in', null=True)),
                ('pm_out', models.DateTimeField(blank=True, help_text='Biometric scan timestamp for PM time-out', null=True)),
                ('is_holiday', models.BooleanField(default=False, help_text='Marked if the day is a holiday (national or local)')),
                ('holiday_type', models.CharField(blank=True, choices=[('regular', 'Regular Holiday'), ('special', 'Special Non-Working Holiday'), ('local', 'Local Holiday')], help_text='Type of holiday — for record/display only. No pay effect per agency rules.', max_length=10, null=True)),
                ('is_restday', models.BooleanField(default=False, help_text='Saturday/Sunday or declared rest day')),
                ('minutes_late', models.IntegerField(default=0, help_text='Total minutes late. No grace period. Any scan after 08:00 is late.')),
                ('hours_undertime', models.DecimalField(decimal_places=2, default=0, help_text='Hours of undertime based on schedule', max_digits=5)),
                ('hours_overtime', models.DecimalField(decimal_places=2, default=0, help_text='Hours beyond PM out (17:00). OT Thank You — no additional pay.', max_digits=5)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Total actual hours worked', max_digits=5)),
                ('am_in_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('to', 'Travel Order'), ('tt', 'Trip Ticket'), ('leave', 'On Leave'), ('holiday', 'Holiday')], help_text='Status flag for AM time-in slot', max_length=10, null=True)),
                ('am_out_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('to', 'Travel Order'), ('tt', 'Trip Ticket'), ('leave', 'On Leave'), ('holiday', 'Holiday')], help_text='Status flag for AM time-out slot', max_length=10, null=True)),
                ('pm_in_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('to', 'Travel Order'), ('tt', 'Trip Ticket'), ('leave', 'On Leave'), ('holiday', 'Holiday')], help_text='Status flag for PM time-in slot', max_length=10, null=True)),
                ('pm_out_status', models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('to', 'Travel Order'), ('tt', 'Trip Ticket'), ('leave', 'On Leave'), ('holiday', 'Holiday')], help_text='Status flag for PM time-out slot', max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, help_text='TO code (e.g. TO#26-02-1375HR), leave type, or manual correction note', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after HR approves. Edit requires audit log reason.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee reference', on_delete=django.db.models.deletion.PROTECT, related_name='dtr_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'DTR Record',
                'verbose_name_plural': 'DTR Records',
                'db_table': 'dtr_records',
                'ordering': ['-dtr_date', 'employee__last_name'],
                'unique_together': {('employee', 'dtr_date')},
            },
        ),
    ]
