# Generated by Django 6.0.3 on 2026-03-10 14:32

import apps.employees.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('division_id', models.AutoField(primary_key=True, serialize=False)),
                ('division_code', models.CharField(help_text='Short code e.g., ORD, FPSSD, FMRED, PFO, TOSS', max_length=20, unique=True)),
                ('division_name', models.CharField(help_text='Full name e.g., Office of the Regional Director', max_length=200)),
                ('work_schedule_type', models.CharField(choices=[('fixed', 'Fixed (8AM-5Pm)'), ('flexible', 'Flexible (FishCore)')], default='fixed', help_text='Fixed = 8AM-5PM | Flexible = FishCore type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'db_table': 'divisions',
                'ordering': ['division_code'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text='e.g. Contract of Service | Job Order | NSAP Enumerator | NSAP Freshwater | FishCore | Adjudication | Permanent', max_length=100)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'Contract of Service'), ('JO', 'Job Order')], help_text='Primary employment classification', max_length=20)),
                ('contribution_scheme', models.CharField(choices=[('GSIS', 'GSIS (Permanent)'), ('SSS', 'SSS (All)'), ('PhilHealth', 'PhilHealth (All)'), ('Pag-Ibig', 'Pag-Ibig (All)')], help_text='GSIS for Permanent, SSS for all others', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payroll Group',
                'verbose_name_plural': 'Payroll Groups',
                'db_table': 'payroll_groups',
                'ordering': ['group_name'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_title', models.CharField(help_text='e.g. Fishery Technologist II,Administrative Aide IV, Driver II', max_length=200)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'Contract of Service'), ('JO', 'Job Order')], help_text='Which employment type this position belongs to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['employment_type', 'position_title'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(help_text='e.g. Regular 8AM-5PM, FishCore Flexible', max_length=100)),
                ('am_in', models.TimeField(default='08:00', help_text='Expected AM time-in')),
                ('am_out', models.TimeField(default='12:00', help_text='Expected AM time-out')),
                ('pm_in', models.TimeField(default='13:00', help_text='Expected PM time-in')),
                ('pm_out', models.TimeField(default='17:00', help_text='Expected PM time-out')),
                ('is_flexible', models.BooleanField(default=False, help_text='TRUE for FishCore flexible schedule')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Total working hours per day (basis for undertime/OT computation)', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'db_table': 'work_schedules',
                'ordering': ['schedule_name'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(help_text='e.g., Planning Unit, Accounting Unit, Aurora Province', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(help_text='Which division this unit belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='employees.division')),
                ('parent_unit', models.ForeignKey(blank=True, help_text='For sub-station: Baler Satellite -> Aurora Brackishwater parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='employees.unit')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['division__division_code', 'unit_name'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(help_text='Internal system ID (auto-generated)', primary_key=True, serialize=False)),
                ('id_number', models.CharField(help_text='Biometric device number e.g. 000000001', max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=10)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('COS', 'Contract of Service'), ('JO', 'Job Order')], help_text='Primary employment classificatin', max_length=20)),
                ('montly_salary', models.DecimalField(decimal_places=2, help_text='Basic monthly salary (HR inputs this)', max_digits=10)),
                ('pera', models.DecimalField(decimal_places=2, default=2000.0, help_text='Personnel Economic Relief Allowance - fiexd ₱2,000 for Permanent', max_digits=10)),
                ('date_hired', models.DateField(help_text='Date of first day of service (used for leave proration)')),
                ('is_active', models.BooleanField(default=True, help_text='Active/Inactive status')),
                ('fingerprint_template', models.BinaryField(blank=True, help_text='Encrypted fingerprint biometric template from device', null=True)),
                ('face_template', models.BinaryField(blank=True, help_text='Encrypted face recognition template from device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, help_text='Assigned division', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.division')),
                ('payroll_group', models.ForeignKey(blank=True, help_text='Which payroll list they belong to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.payrollgroup')),
                ('position', models.ForeignKey(blank=True, help_text='Job position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position')),
                ('unit', models.ForeignKey(blank=True, help_text='Assigned unit/section', null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.unit')),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('emp_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateField(help_text='Date when this schedule assignment become active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee reference', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
                ('schedule', models.ForeignKey(help_text='Schedule reference', on_delete=django.db.models.deletion.PROTECT, related_name='employee_schedules', to='employees.workschedule')),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedules',
                'db_table': 'employee_schedules',
                'ordering': ['employee__last_name', '-effective_date'],
                'unique_together': {('employee', 'effective_date')},
            },
            bases=(apps.employees.models.PhilippinesTimeMixin, models.Model),
        ),
    ]
