# Generated by Django 6.0.3 on 2026-03-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='montly_salary',
            new_name='monthly_salary',
        ),
    ]
