# Generated by Django 6.0.3 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_address_employee_biometric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flagger. T = hidden from all lists, F = active employee'),
        ),
    ]
