# Generated by Django 6.0.3 on 2026-03-28 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_employee_is_active_remove_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='default_schedule',
            field=models.ForeignKey(blank=True, help_text='Default work schedule for all employees in this division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_defaults', to='employees.workschedule'),
        ),
        migrations.AddField(
            model_name='unit',
            name='default_schedule',
            field=models.ForeignKey(blank=True, help_text='Overrides division schedule for employees in this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_defaults', to='employees.workschedule'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='flex_start_earliest',
            field=models.TimeField(default='07:00', help_text='Earliest allowed time-in for flex schedules (07:00)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='flex_start_latest',
            field=models.TimeField(default='08:00', help_text='Latest on-time arrival. After this = late, even for flex.'),
        ),
    ]
