# Generated by Django 6.0.3 on 2026-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_division_default_schedule_unit_default_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free schedule - no deductions ever computed.Employee is always present in any scan existsUser for FishCore or any group with fully flexible hours.'),
        ),
    ]
