# Generated by Django 6.0.3 on 2026-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_workschedule_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='source',
            field=models.CharField(choices=[('personal', 'Personal Override'), ('pushed', 'Pushed from Group')], default='personal', help_text='personal = HR set directly on the employees.Pushed = auto-applied from division/unit schedule push.Only personal override block future group pushes.', max_length=10),
        ),
    ]
