# Generated by Django 6.0.3 on 2026-04-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeeschedule_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text='Jr., Sr., III, etc.', max_length=10),
        ),
    ]
